// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.InactiveUsers;
using AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.Me;
using AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.Tenant;
using AlphaSquad.Lmt.Application.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Checkins
{
    /// <summary>
    /// Builds and executes requests for operations under \api\checkins
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CheckinsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The inactiveUsers property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.InactiveUsers.InactiveUsersRequestBuilder InactiveUsers
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.InactiveUsers.InactiveUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.Me.MeRequestBuilder Me
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenant property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.Tenant.TenantRequestBuilder Tenant
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.Tenant.TenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CheckinsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/checkins", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CheckinsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/checkins", rawUrl)
        {
        }
        /// <summary>
        /// Cria um registro de entrada no tenant atual, respeitando a regra de um check-in por dia.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.CheckInResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AlphaSquad.Lmt.Application.ApiClient.Models.CheckInResponse?> PostAsync(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateCheckInRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AlphaSquad.Lmt.Application.ApiClient.Models.CheckInResponse> PostAsync(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateCheckInRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::AlphaSquad.Lmt.Application.ApiClient.Models.CheckInResponse>(requestInfo, global::AlphaSquad.Lmt.Application.ApiClient.Models.CheckInResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Cria um registro de entrada no tenant atual, respeitando a regra de um check-in por dia.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateCheckInRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateCheckInRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CheckinsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
