// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug
{
    /// <summary>
    /// Builds and executes requests for operations under \api\tenants\by-slug
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BySlugRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AlphaSquad.ApiClient.api.tenants.bySlug.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.Item.WithSlugItemRequestBuilder"/></returns>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.Item.WithSlugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("slug", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.Item.WithSlugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.BySlugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BySlugRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/tenants/by-slug", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.BySlugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BySlugRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/tenants/by-slug", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
