// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AcademyEventResponseCursorFeedResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The hasMore property</summary>
        public bool? HasMore { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponse>? Items { get; set; }
#nullable restore
#else
        public List<global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponse> Items { get; set; }
#endif
        /// <summary>The nextCursor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponseCursorFeedResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponseCursorFeedResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponseCursorFeedResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hasMore", n => { HasMore = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponse>(global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nextCursor", n => { NextCursor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("hasMore", HasMore);
            writer.WriteCollectionOfObjectValues<global::AlphaSquad.Lmt.Application.ApiClient.Models.AcademyEventResponse>("items", Items);
            writer.WriteStringValue("nextCursor", NextCursor);
        }
    }
}
#pragma warning restore CS0618
