// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CloseMonthlyRankingRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The firstPlacePrize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstPlacePrize { get; set; }
#nullable restore
#else
        public string FirstPlacePrize { get; set; }
#endif
        /// <summary>The month property</summary>
        public int? Month { get; set; }
        /// <summary>The secondPlacePrize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondPlacePrize { get; set; }
#nullable restore
#else
        public string SecondPlacePrize { get; set; }
#endif
        /// <summary>The thirdPlacePrize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThirdPlacePrize { get; set; }
#nullable restore
#else
        public string ThirdPlacePrize { get; set; }
#endif
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.CloseMonthlyRankingRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.CloseMonthlyRankingRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.CloseMonthlyRankingRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "firstPlacePrize", n => { FirstPlacePrize = n.GetStringValue(); } },
                { "month", n => { Month = n.GetIntValue(); } },
                { "secondPlacePrize", n => { SecondPlacePrize = n.GetStringValue(); } },
                { "thirdPlacePrize", n => { ThirdPlacePrize = n.GetStringValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("firstPlacePrize", FirstPlacePrize);
            writer.WriteIntValue("month", Month);
            writer.WriteStringValue("secondPlacePrize", SecondPlacePrize);
            writer.WriteStringValue("thirdPlacePrize", ThirdPlacePrize);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
