// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAcademyEventRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allowParticipation property</summary>
        public bool? AllowParticipation { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endsAt property</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The isOutdoorEvent property</summary>
        public bool? IsOutdoorEvent { get; set; }
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The mediaId property</summary>
        public Guid? MediaId { get; set; }
        /// <summary>The startsAt property</summary>
        public DateTimeOffset? StartsAt { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateAcademyEventRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateAcademyEventRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateAcademyEventRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowParticipation", n => { AllowParticipation = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endsAt", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isOutdoorEvent", n => { IsOutdoorEvent = n.GetBoolValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "mediaId", n => { MediaId = n.GetGuidValue(); } },
                { "startsAt", n => { StartsAt = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowParticipation", AllowParticipation);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endsAt", EndsAt);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isOutdoorEvent", IsOutdoorEvent);
            writer.WriteStringValue("location", Location);
            writer.WriteGuidValue("mediaId", MediaId);
            writer.WriteDateTimeOffsetValue("startsAt", StartsAt);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
