// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExerciseAssignmentRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The exerciseId property</summary>
        public Guid? ExerciseId { get; set; }
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The order property</summary>
        public int? Order { get; set; }
        /// <summary>The reps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reps { get; set; }
#nullable restore
#else
        public string Reps { get; set; }
#endif
        /// <summary>The restTime property</summary>
        public int? RestTime { get; set; }
        /// <summary>The sets property</summary>
        public int? Sets { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.ExerciseAssignmentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.ExerciseAssignmentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.ExerciseAssignmentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "exerciseId", n => { ExerciseId = n.GetGuidValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "reps", n => { Reps = n.GetStringValue(); } },
                { "restTime", n => { RestTime = n.GetIntValue(); } },
                { "sets", n => { Sets = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("exerciseId", ExerciseId);
            writer.WriteStringValue("notes", Notes);
            writer.WriteIntValue("order", Order);
            writer.WriteStringValue("reps", Reps);
            writer.WriteIntValue("restTime", RestTime);
            writer.WriteIntValue("sets", Sets);
        }
    }
}
#pragma warning restore CS0618
