// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GymClassResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The capacity property</summary>
        public int? Capacity { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endsAt property</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The instructorName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstructorName { get; set; }
#nullable restore
#else
        public string InstructorName { get; set; }
#endif
        /// <summary>The instructorUserId property</summary>
        public Guid? InstructorUserId { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The isSpecialClass property</summary>
        public bool? IsSpecialClass { get; set; }
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The startsAt property</summary>
        public DateTimeOffset? StartsAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.GymClassResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.GymClassResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.GymClassResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "capacity", n => { Capacity = n.GetIntValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endsAt", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "instructorName", n => { InstructorName = n.GetStringValue(); } },
                { "instructorUserId", n => { InstructorUserId = n.GetGuidValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isSpecialClass", n => { IsSpecialClass = n.GetBoolValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "startsAt", n => { StartsAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("capacity", Capacity);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endsAt", EndsAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("instructorName", InstructorName);
            writer.WriteGuidValue("instructorUserId", InstructorUserId);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isSpecialClass", IsSpecialClass);
            writer.WriteStringValue("location", Location);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("startsAt", StartsAt);
        }
    }
}
#pragma warning restore CS0618
