// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MonthlyWinnerHistoryEntryResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The generatedAt property</summary>
        public DateTimeOffset? GeneratedAt { get; set; }
        /// <summary>The month property</summary>
        public int? Month { get; set; }
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The prizeDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrizeDescription { get; set; }
#nullable restore
#else
        public string PrizeDescription { get; set; }
#endif
        /// <summary>The totalPoints property</summary>
        public double? TotalPoints { get; set; }
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The userName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.MonthlyWinnerHistoryEntryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.MonthlyWinnerHistoryEntryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.MonthlyWinnerHistoryEntryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "generatedAt", n => { GeneratedAt = n.GetDateTimeOffsetValue(); } },
                { "month", n => { Month = n.GetIntValue(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "prizeDescription", n => { PrizeDescription = n.GetStringValue(); } },
                { "totalPoints", n => { TotalPoints = n.GetDoubleValue(); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("generatedAt", GeneratedAt);
            writer.WriteIntValue("month", Month);
            writer.WriteIntValue("position", Position);
            writer.WriteStringValue("prizeDescription", PrizeDescription);
            writer.WriteDoubleValue("totalPoints", TotalPoints);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteStringValue("userName", UserName);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
