// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StoreOrderDetailResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The adminNotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdminNotes { get; set; }
#nullable restore
#else
        public string AdminNotes { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The customerNotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerNotes { get; set; }
#nullable restore
#else
        public string CustomerNotes { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse>? Items { get; set; }
#nullable restore
#else
        public List<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse> Items { get; set; }
#endif
        /// <summary>The lastUpdatedByUserId property</summary>
        public Guid? LastUpdatedByUserId { get; set; }
        /// <summary>The lastUpdatedByUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedByUserName { get; set; }
#nullable restore
#else
        public string LastUpdatedByUserName { get; set; }
#endif
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>The totalAmount property</summary>
        public double? TotalAmount { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The userEmail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserEmail { get; set; }
#nullable restore
#else
        public string UserEmail { get; set; }
#endif
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The userName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderDetailResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderDetailResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderDetailResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adminNotes", n => { AdminNotes = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customerNotes", n => { CustomerNotes = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse>(global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastUpdatedByUserId", n => { LastUpdatedByUserId = n.GetGuidValue(); } },
                { "lastUpdatedByUserName", n => { LastUpdatedByUserName = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "totalAmount", n => { TotalAmount = n.GetDoubleValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "userEmail", n => { UserEmail = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("adminNotes", AdminNotes);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("customerNotes", CustomerNotes);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse>("items", Items);
            writer.WriteGuidValue("lastUpdatedByUserId", LastUpdatedByUserId);
            writer.WriteStringValue("lastUpdatedByUserName", LastUpdatedByUserName);
            writer.WriteIntValue("status", Status);
            writer.WriteDoubleValue("totalAmount", TotalAmount);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("userEmail", UserEmail);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteStringValue("userName", UserName);
        }
    }
}
#pragma warning restore CS0618
