// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StoreOrderItemResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The lineTotal property</summary>
        public double? LineTotal { get; set; }
        /// <summary>The productId property</summary>
        public Guid? ProductId { get; set; }
        /// <summary>The productName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductName { get; set; }
#nullable restore
#else
        public string ProductName { get; set; }
#endif
        /// <summary>The productVariantId property</summary>
        public Guid? ProductVariantId { get; set; }
        /// <summary>The quantity property</summary>
        public int? Quantity { get; set; }
        /// <summary>The unitPrice property</summary>
        public double? UnitPrice { get; set; }
        /// <summary>The variantColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VariantColor { get; set; }
#nullable restore
#else
        public string VariantColor { get; set; }
#endif
        /// <summary>The variantName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VariantName { get; set; }
#nullable restore
#else
        public string VariantName { get; set; }
#endif
        /// <summary>The variantSize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VariantSize { get; set; }
#nullable restore
#else
        public string VariantSize { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderItemResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetGuidValue(); } },
                { "lineTotal", n => { LineTotal = n.GetDoubleValue(); } },
                { "productId", n => { ProductId = n.GetGuidValue(); } },
                { "productName", n => { ProductName = n.GetStringValue(); } },
                { "productVariantId", n => { ProductVariantId = n.GetGuidValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetDoubleValue(); } },
                { "variantColor", n => { VariantColor = n.GetStringValue(); } },
                { "variantName", n => { VariantName = n.GetStringValue(); } },
                { "variantSize", n => { VariantSize = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("id", Id);
            writer.WriteDoubleValue("lineTotal", LineTotal);
            writer.WriteGuidValue("productId", ProductId);
            writer.WriteStringValue("productName", ProductName);
            writer.WriteGuidValue("productVariantId", ProductVariantId);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteDoubleValue("unitPrice", UnitPrice);
            writer.WriteStringValue("variantColor", VariantColor);
            writer.WriteStringValue("variantName", VariantName);
            writer.WriteStringValue("variantSize", VariantSize);
        }
    }
}
#pragma warning restore CS0618
