// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserMembershipHistoryResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The changedByUserId property</summary>
        public Guid? ChangedByUserId { get; set; }
        /// <summary>The changedByUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChangedByUserName { get; set; }
#nullable restore
#else
        public string ChangedByUserName { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The durationDays property</summary>
        public int? DurationDays { get; set; }
        /// <summary>The endsAt property</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The membershipPlanId property</summary>
        public Guid? MembershipPlanId { get; set; }
        /// <summary>The planName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanName { get; set; }
#nullable restore
#else
        public string PlanName { get; set; }
#endif
        /// <summary>The planPrice property</summary>
        public double? PlanPrice { get; set; }
        /// <summary>The startsAt property</summary>
        public DateTimeOffset? StartsAt { get; set; }
        /// <summary>The statusReason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReason { get; set; }
#nullable restore
#else
        public string StatusReason { get; set; }
#endif
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The userName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.UserMembershipHistoryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.UserMembershipHistoryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.UserMembershipHistoryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "changedByUserId", n => { ChangedByUserId = n.GetGuidValue(); } },
                { "changedByUserName", n => { ChangedByUserName = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "durationDays", n => { DurationDays = n.GetIntValue(); } },
                { "endsAt", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "membershipPlanId", n => { MembershipPlanId = n.GetGuidValue(); } },
                { "planName", n => { PlanName = n.GetStringValue(); } },
                { "planPrice", n => { PlanPrice = n.GetDoubleValue(); } },
                { "startsAt", n => { StartsAt = n.GetDateTimeOffsetValue(); } },
                { "statusReason", n => { StatusReason = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("changedByUserId", ChangedByUserId);
            writer.WriteStringValue("changedByUserName", ChangedByUserName);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteIntValue("durationDays", DurationDays);
            writer.WriteDateTimeOffsetValue("endsAt", EndsAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteGuidValue("membershipPlanId", MembershipPlanId);
            writer.WriteStringValue("planName", PlanName);
            writer.WriteDoubleValue("planPrice", PlanPrice);
            writer.WriteDateTimeOffsetValue("startsAt", StartsAt);
            writer.WriteStringValue("statusReason", StatusReason);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteStringValue("userName", UserName);
        }
    }
}
#pragma warning restore CS0618
