// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserWithoutRecentCheckInResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activePlanId property</summary>
        public Guid? ActivePlanId { get; set; }
        /// <summary>The activePlanName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivePlanName { get; set; }
#nullable restore
#else
        public string ActivePlanName { get; set; }
#endif
        /// <summary>The daysWithoutCheckIn property</summary>
        public int? DaysWithoutCheckIn { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The lastCheckedInAt property</summary>
        public DateTimeOffset? LastCheckedInAt { get; set; }
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The userName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>The userRole property</summary>
        public int? UserRole { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutRecentCheckInResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutRecentCheckInResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutRecentCheckInResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activePlanId", n => { ActivePlanId = n.GetGuidValue(); } },
                { "activePlanName", n => { ActivePlanName = n.GetStringValue(); } },
                { "daysWithoutCheckIn", n => { DaysWithoutCheckIn = n.GetIntValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "lastCheckedInAt", n => { LastCheckedInAt = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
                { "userRole", n => { UserRole = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("activePlanId", ActivePlanId);
            writer.WriteStringValue("activePlanName", ActivePlanName);
            writer.WriteIntValue("daysWithoutCheckIn", DaysWithoutCheckIn);
            writer.WriteStringValue("email", Email);
            writer.WriteDateTimeOffsetValue("lastCheckedInAt", LastCheckedInAt);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteStringValue("userName", UserName);
            writer.WriteIntValue("userRole", UserRole);
        }
    }
}
#pragma warning restore CS0618
