// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Auth;
using AlphaSquad.Lmt.Application.ApiClient.Api.Checkins;
using AlphaSquad.Lmt.Application.ApiClient.Api.Classes;
using AlphaSquad.Lmt.Application.ApiClient.Api.Events;
using AlphaSquad.Lmt.Application.ApiClient.Api.Exercises;
using AlphaSquad.Lmt.Application.ApiClient.Api.Gamification;
using AlphaSquad.Lmt.Application.ApiClient.Api.Legal;
using AlphaSquad.Lmt.Application.ApiClient.Api.Media;
using AlphaSquad.Lmt.Application.ApiClient.Api.Plans;
using AlphaSquad.Lmt.Application.ApiClient.Api.Profile;
using AlphaSquad.Lmt.Application.ApiClient.Api.Social;
using AlphaSquad.Lmt.Application.ApiClient.Api.Store;
using AlphaSquad.Lmt.Application.ApiClient.Api.Tenants;
using AlphaSquad.Lmt.Application.ApiClient.Api.Users;
using AlphaSquad.Lmt.Application.ApiClient.Api.Workouts;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkins property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder Checkins
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Checkins.CheckinsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The classes property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.ClassesRequestBuilder Classes
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.ClassesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Events.EventsRequestBuilder Events
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exercises property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Exercises.ExercisesRequestBuilder Exercises
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Exercises.ExercisesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gamification property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.GamificationRequestBuilder Gamification
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.GamificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The legal property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Legal.LegalRequestBuilder Legal
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Legal.LegalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The media property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Media.MediaRequestBuilder Media
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plans property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.PlansRequestBuilder Plans
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.PlansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Profile.ProfileRequestBuilder Profile
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The social property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Social.SocialRequestBuilder Social
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Social.SocialRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The store property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.StoreRequestBuilder Store
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.StoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenants property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.TenantsRequestBuilder Tenants
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.TenantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Users.UsersRequestBuilder Users
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workouts property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Workouts.WorkoutsRequestBuilder Workouts
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Workouts.WorkoutsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
