// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug;
using AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Current;
using AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Tenants
{
    /// <summary>
    /// Builds and executes requests for operations under \api\tenants
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TenantsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bySlug property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.BySlugRequestBuilder BySlug
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.BySlug.BySlugRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The current property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Current.CurrentRequestBuilder Current
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Current.CurrentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the AlphaSquad.Lmt.Application.ApiClient.api.tenants.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item.TenantsItemRequestBuilder"/></returns>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item.TenantsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item.TenantsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AlphaSquad.Lmt.Application.ApiClient.api.tenants.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item.TenantsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item.TenantsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.Item.TenantsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.TenantsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/tenants", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Tenants.TenantsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/tenants", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
