// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item;
using AlphaSquad.Lmt.Application.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me
{
    /// <summary>
    /// Builds and executes requests for operations under \api\store\orders\me
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AlphaSquad.ApiClient.api.store.orders.me.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item.MeItemRequestBuilder"/></returns>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item.MeItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item.MeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AlphaSquad.ApiClient.api.store.orders.me.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item.MeItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item.MeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.Item.MeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/store/orders/me{?page*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/store/orders/me{?page*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// Retorna o historico paginado de pedidos realizados pelo proprio usuario na loja do tenant.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderListItemResponsePagedResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderListItemResponsePagedResponse?> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder.MeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderListItemResponsePagedResponse> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder.MeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderListItemResponsePagedResponse>(requestInfo, global::AlphaSquad.Lmt.Application.ApiClient.Models.StoreOrderListItemResponsePagedResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retorna o historico paginado de pedidos realizados pelo proprio usuario na loja do tenant.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder.MeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder.MeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retorna o historico paginado de pedidos realizados pelo proprio usuario na loja do tenant.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MeRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Me.MeRequestBuilder.MeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
