// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\classes\bookings\by-user\{userId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/classes/bookings/by-user/{userId}{?dateFrom*,dateTo*,onlyActiveClasses*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/classes/bookings/by-user/{userId}{?dateFrom*,dateTo*,onlyActiveClasses*}", rawUrl)
        {
        }
        /// <summary>
        /// Retorna as reservas vinculadas ao aluno informado dentro do tenant atual, com filtros opcionais por status e periodo.
        /// </summary>
        /// <returns>A List&lt;global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse>?> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse>> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse>(requestInfo, global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Retorna as reservas vinculadas ao aluno informado dentro do tenant atual, com filtros opcionais por status e periodo.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retorna as reservas vinculadas ao aluno informado dentro do tenant atual, com filtros opcionais por status e periodo.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUserItemRequestBuilderGetQueryParameters 
        {
            [QueryParameter("dateFrom")]
            public DateTimeOffset? DateFrom { get; set; }
            [QueryParameter("dateTo")]
            public DateTimeOffset? DateTo { get; set; }
            [QueryParameter("onlyActiveClasses")]
            public bool? OnlyActiveClasses { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUserItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Bookings.ByUser.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
