// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item;
using AlphaSquad.Lmt.Application.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings
{
    /// <summary>
    /// Builds and executes requests for operations under \api\classes\{id}\bookings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AlphaSquad.Lmt.Application.ApiClient.api.classes.item.bookings.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item.WithBookingItemRequestBuilder"/></returns>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item.WithBookingItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("bookingId", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item.WithBookingItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AlphaSquad.Lmt.Application.ApiClient.api.classes.item.bookings.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item.WithBookingItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item.WithBookingItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("bookingId", position);
                return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.Item.WithBookingItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/classes/{id}/bookings{?onlyActiveClasses*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/classes/{id}/bookings{?onlyActiveClasses*}", rawUrl)
        {
        }
        /// <summary>
        /// Retorna as reservas da aula informada, com dados do aluno e ordenacao por data de reserva.
        /// </summary>
        /// <returns>A List&lt;global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse>?> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse>> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse>(requestInfo, global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingManagementResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Permite que a gestão da academia confirme uma reserva em nome de um aluno, útil para recepção e atendimento presencial.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingResponse?> PostAsync(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateClassBookingForUserRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingResponse> PostAsync(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateClassBookingForUserRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingResponse>(requestInfo, global::AlphaSquad.Lmt.Application.ApiClient.Models.ClassBookingResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retorna as reservas da aula informada, com dados do aluno e ordenacao por data de reserva.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Permite que a gestão da academia confirme uma reserva em nome de um aluno, útil para recepção e atendimento presencial.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateClassBookingForUserRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AlphaSquad.Lmt.Application.ApiClient.Models.CreateClassBookingForUserRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retorna as reservas da aula informada, com dados do aluno e ordenacao por data de reserva.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("onlyActiveClasses")]
            public bool? OnlyActiveClasses { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Classes.Item.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
