// App namespaces
global using AlphaSquad.Shared.Enums;
global using AlphaSquad.Infrastructure.Persistence;
global using AlphaSquad.Infrastructure.Storage;
global using AlphaSquad.Shared.Contracts;
// System namespaces
global using System;
global using System.Collections.Generic;
global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using System.Text.Json;
global using Microsoft.Extensions.Options;
global using StackExchange.Redis;
global using Amazon.S3;
global using Amazon.S3.Model;