// App namespaces
global using AlphaSquad.Shared.Enums;
// System namespaces
global using System;
global using System.Collections.Generic;
global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using BCrypt.Net;