// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\plans\inactive-users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InactiveUsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InactiveUsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/plans/inactive-users{?daysWithoutPlan*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InactiveUsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/plans/inactive-users{?daysWithoutPlan*}", rawUrl)
        {
        }
        /// <summary>
        /// Ajuda a academia a identificar alunos sem plano ativo por um periodo minimo para futuras campanhas de reativacao.
        /// </summary>
        /// <returns>A List&lt;global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutActivePlanResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutActivePlanResponse>?> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder.InactiveUsersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutActivePlanResponse>> GetAsync(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder.InactiveUsersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutActivePlanResponse>(requestInfo, global::AlphaSquad.Lmt.Application.ApiClient.Models.UserWithoutActivePlanResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Ajuda a academia a identificar alunos sem plano ativo por um periodo minimo para futuras campanhas de reativacao.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder.InactiveUsersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder.InactiveUsersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Ajuda a academia a identificar alunos sem plano ativo por um periodo minimo para futuras campanhas de reativacao.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InactiveUsersRequestBuilderGetQueryParameters 
        {
            [QueryParameter("daysWithoutPlan")]
            public int? DaysWithoutPlan { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InactiveUsersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AlphaSquad.Lmt.Application.ApiClient.Api.Plans.InactiveUsers.InactiveUsersRequestBuilder.InactiveUsersRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
