// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders;
using AlphaSquad.Lmt.Application.ApiClient.Api.Store.Products;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Store
{
    /// <summary>
    /// Builds and executes requests for operations under \api\store
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StoreRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The orders property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.OrdersRequestBuilder Orders
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Products.ProductsRequestBuilder Products
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.StoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoreRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/store", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.StoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoreRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/store", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
