// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Me;
using AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking;
using AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Rules;
using AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Winners;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Gamification
{
    /// <summary>
    /// Builds and executes requests for operations under \api\gamification
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GamificationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The me property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Me.MeRequestBuilder Me
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ranking property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.RankingRequestBuilder Ranking
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.RankingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rules property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Rules.RulesRequestBuilder Rules
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Rules.RulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The winners property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Winners.WinnersRequestBuilder Winners
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Winners.WinnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.GamificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamificationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/gamification", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.GamificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamificationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/gamification", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
