// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.Monthly;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking
{
    /// <summary>
    /// Builds and executes requests for operations under \api\gamification\ranking
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RankingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The monthly property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.Monthly.MonthlyRequestBuilder Monthly
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.Monthly.MonthlyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.RankingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RankingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/gamification/ranking", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Gamification.Ranking.RankingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RankingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/gamification/ranking", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
