// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Item.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\store\orders\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrdersItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The status property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Item.Status.StatusRequestBuilder Status
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Item.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Item.OrdersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/store/orders/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Store.Orders.Item.OrdersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/store/orders/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
