// App namespaces
global using AlphaSquad.Infrastructure.Persistence;
global using AlphaSquad.Shared.Contracts;
global using AlphaSquad.Api.Features.Auth;
global using AlphaSquad.Api.Features.Tenants;
global using AlphaSquad.Api.DependencyInjections;
global using AlphaSquad.Infrastructure.Caching;
global using AlphaSquad.Infrastructure.Storage;
global using AlphaSquad.Api.Features.Media;
global using AlphaSquad.Shared.Helpers;
// System namespaces
global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using AlphaSquad.Infrastructure.Auth;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using StackExchange.Redis;
global using System.Security.Claims;
global using Amazon.S3;
global using Microsoft.AspNetCore.Http.HttpResults;