// <auto-generated/>
#pragma warning disable CS0618
using AlphaSquad.Lmt.Application.ApiClient.Api.Auth.ChangePassword;
using AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Login;
using AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Logout;
using AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Me;
using AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Refresh;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AlphaSquad.Lmt.Application.ApiClient.Api.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changePassword property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.ChangePassword.ChangePasswordRequestBuilder ChangePassword
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.ChangePassword.ChangePasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Login.LoginRequestBuilder Login
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Me.MeRequestBuilder Me
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AlphaSquad.Lmt.Application.ApiClient.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
